# Generated by Django 6.1.1 on 2026-09-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
