# Generated by Django 6.1.1 on 2026-09-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_create_at_job_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
    ]
